platform :ios, '8.0'

target 'ReactiveObjC-Use-Demo' do
    pod 'ReactiveObjC'
    pod 'Masonry'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'AFNetworking'
    # 侧滑手势
    pod 'FDFullscreenPopGesture'            , '1.1'
    
    #########  Category  #########
    # 非常强大的Objective-C库的扩展
    pod 'libextobjc'                        , '0.4.1'
    
    # UI block
    pod 'BlocksKit'                         , '2.2.5'
    # UICollectionView左对齐布局
    pod 'UICollectionViewLeftAlignedLayout' , '1.0.2'
    
    
    # FaceBook KVO（优雅的代替系统原生的KVO）
    pod 'KVOController'                     , '1.2.0'
    
    # FaceBook 内存分析工具 其中包括了：FBAllocationTracker 和 FBRetainCycleDetector两个工具
    pod 'FBMemoryProfiler'                  , '0.1.3'
    
end
