platform :ios, '8.0'

target 'ReactiveObjC-Use-Demo' do
    pod 'ReactiveObjC'
    pod 'Masonry'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'AFNetworking'
    # 侧滑手势
    pod 'FDFullscreenPopGesture'            , '1.1'
    
    #########  Category  #########
    # 非常强大的Objective-C库的扩展
    pod 'libextobjc'                        , '0.4.1'
    
    # UI block
    pod 'BlocksKit'                         , '2.2.5'
    # UICollectionView左对齐布局
    pod 'UICollectionViewLeftAlignedLayout' , '1.0.2'
    
    
    # FaceBook KVO（优雅的代替系统原生的KVO）
    pod 'KVOController'                     , '1.2.0'
    
    # FaceBook 内存分析工具 其中包括了：FBAllocationTracker 和 FBRetainCycleDetector两个工具
    pod 'FBMemoryProfiler'                  , '0.1.3'
    
    # 颜色分类
    pod 'Colours'                           , '5.13.0'
    # YYKit 的一套分类
    pod 'YYCategories'                      , '1.0.4'
    # 富文本
    pod 'YYText'                            , '1.0.7'
    # 字典转模型
    pod 'YYModel'                           , '1.0.4'
    # YYImage
    pod 'YYImage'                           , '1.0.4'
    # webP
    pod 'YYImage/WebP'
    # 高性能的 iOS 缓存框架
    pod 'YYCache'                           , '1.0.4'
    # 高性能的 iOS 异步图像加载框架。
    pod 'YYWebImage'                        , '1.0.5'
    # iOS 键盘监听管理工具
    pod 'YYKeyboardManager'                 , '1.0.1'
    # iOS 全局并发队列管理工具
    pod 'YYDispatchQueuePool'               , '1.0'
    # iOS 异步绘制与显示的工具
    pod 'YYAsyncLayer'                      , '1.0'
    # 钥匙串存储
    pod 'SAMKeychain'                       , '1.5.2'
    # 加密
    pod 'CocoaSecurity'                     , '1.2.4'
    
    # 字典转模型 该项目使用YYModel
    pod 'MJExtension'                       , '3.0.13'
    pod 'MJRefresh'                         , '3.1.12'
    # 状态栏通知
    pod 'JDStatusBarNotification'           , '1.5.5'
end
